#!/bin/zsh

# 先提交目前的内容

git add -A

git commit -m 'update docs'

git pull

git push

# 然后将build内容推送到远程
cd build

git init

git remote add origin https://github.com/HenryGaoGH/yasee.io.git

git add -A

git commit -m 'update docs'

git config http.postBuffer 31457280

git push -f -u origin main

cd ..
