#!/bin/zsh

# 先提交目前的内容

git add -A

git commit -m 'update docs'

git pull

git push

# 然后将build内容推送到远程
cd build

git init

git remote add origin https://github.com/HenryGaoGH/yasee.io.git

git add -A

git commit -m 'update docs'

git config http.postBuffer 61943040

git push -f origin main


# 推送到 10.0.0.61 服务器
rsync -avz ./ root@10.0.0.61:/yasee/page/documents

ssh root@10.0.0.61 "systemctl restart nginx && exit"

echo "Files have been uploaded to 10.0.0.61:/yasee/page/documents"

cd ..
