import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mobileSidebarId: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mobileSidebarId: [
    {
      type: "doc",
      label: "欢迎👏",
      id: "welcome_yasee",
    },
    {
      type: "doc",
      label: "通用流程介绍",
      id: "comm/comm_third_process",
    },
    {
      type: "doc",
      label: "WIFI 设备 流程介绍",
      id: "comm/comm_third_process_wifi",
    },
    {
      type: "doc",
      label: "BLE 检测流程详解",
      id: "comm/comm_third_process_ble",
    },
    {
      type: "doc",
      label: "线上分析接口",
      id: "comm/comm_third_api",
    },
    {
      type: "doc",
      label: "样机寄送规范",
      id: "comm/comm_third_demo_process",
    },
    {
      type: "category",
      label: "Yasee SDK(Android)",
      items: [
        "yasee_android/intro",
        "yasee_android/intro_en",
        "yasee_android/demo_word",
        "yasee_android/demo_word_en",
        "yasee_android/baogao",
        "yasee_android/baogao_en",
        "yasee_android/tmdVSwl",
        "yasee_android/tmdVSwl_en",
        "yasee_android/download",
      ],
    },
    {
      type: "category",
      label: "Yasee SDK(iOS)",
      items: [
        "yasee_ios/used_doc",
        "yasee_ios/used_doc_en",
        "yasee_ios/demo",
        "yasee_ios/demo_en",
        "yasee_ios/power_doc",
        "yasee_ios/power_doc_en",
        "yasee_ios/download",
      ],
    },
    {
      type: "category",
      label: "Yasee Plugin(Flutter)",
      items: ["yasee_flutter/used_doc", "yasee_flutter/demo"],
    },
  ],
  thirdId: [
    {
      type: "doc",
      label: "欢迎👏",
      id: "welcome_third",
    },
    {
      type: "doc",
      label: "物料送寄规范(生态合作)",
      id: "third/yasee_ship_spec",
    },
    {
      type: "doc",
      label: "了解 Yasee 生态融合设计理念",
      id: "third/yasee_third_process",
    },
    {
      type: "doc",
      label: "协议对接方式(推荐)",
      id: "third/ble_protol",
    },
    {
      type: "doc",
      label: "BLE Hook 方式",
      id: "third/ble_hook",
    },
  ],
  widgetsId: [
    {
      type: "doc",
      label: "欢迎👏",
      id: "widgets/all_widgets",
    },
  ],
  innerId: [
    {
      type: "doc",
      label: "欢迎👏",
      id: "inner/welcome_inner",
    },
    {
      type: "category",
      label: "报告",
      items: [
        "inner/reports/replace_yasee_sdk",
        "inner/reports/replace_yasee",
        "inner/reports/report_yucheng",
        "inner/reports/report_battery_pullout",
        "inner/reports/replace_merge_bhy",
        "inner/reports/report_ios_ble_reconnect",
        "inner/reports/report_serial",
        "inner/reports/report_massship",
        "inner/reports/report_maizhen",
        "inner/reports/report_maizhen_luoji",
        "inner/reports/report_sdk_1v1",
        "inner/reports/report_health",
      ],
    },
    {
      type: "category",
      label: "项目",
      items: [
        "inner/pms/pm_24_10",
        "inner/pms/pm_24_11",
        "inner/pms/pm_24_12",
        "inner/pms/pm_25_02",
      ],
    },
    {
      type: "category",
      label: "协议",
      items: [
        "inner/protocols/protocol_ble",
        "inner/protocols/protocol_history",
      ],
    },
  ],
  historyId: [
    {
      type: "category",
      label: "Android",
      items: [
        "historys/android_intro_24_10_05",
        "historys/android_intro_25_03_06",
      ],
    },
  ],
};

export default sidebars;
