import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mobileSidebarId: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mobileSidebarId: [
    {
      type: 'doc',
      label: '欢迎👏',
      id: 'welcome_yasee',
    },
    // {
    //   type: 'category',
    //   label: 'Git 工作流程',
    //   items: [
    //     'git_process/mobile_branch'
    //   ],
    // },
    {
      type: 'category',
      label: 'Yasee SDK(Android)',
      items: [
        'yasee_android/intro',
        'yasee_android/demo_word',
        'yasee_android/baogao',
        'yasee_android/tmdVSwl',
      ],
    },
    {
      type: 'category',
      label: 'Yasee SDK(iOS)',
      items: [
        'yasee_ios/used_doc',
        'yasee_ios/demo',
        'yasee_ios/power_doc',
      ],
    },
    {
      type: 'category',
      label: 'Yasee Plugin(Flutter)',
      items: [
        'yasee_flutter/used_doc',
        'yasee_flutter/demo'
      ],
    }
  ],
  thirdId: [
    {
      type: 'doc',
      label: '欢迎👏',
      id: 'welcome_third',
    },
    {
      type: 'doc',
      label: '了解 Yasee 协议模块设计理念',
      id: 'third/yasee_third_process',
    },
    {
      type: 'doc',
      label: '协议对接方式(推荐)',
      id: 'third/ble_protol',
    },
    {
      type: 'doc',
      label: 'BLE Hook 方式(不推荐)',
      id: 'third/ble_hook',
    },
  ],
  widgetsId:[
    {
      type: 'doc',
      label: '欢迎👏',
      id: 'widgets/all_widgets',
    },
  ],
  innerId :[
    {
      type: 'doc',
      label: '欢迎👏',
      id: 'inner/welcome_inner',
    },
    {
      type: 'category',
      label: '报告',
      items: [
        'inner/reports/replace_yasee_sdk',
        'inner/reports/replace_yasee',
        'inner/reports/report_yucheng',
      ],
    },
    {
      type: 'category',
      label: '项目',
      items: [
        'inner/pms/pm_24_10'
      ],
    },
  ],
};

export default sidebars;
