{"topicSections":[{"generated":true,"title":"Articles","identifiers":["doc:\/\/com.yasee.yasee\/documentation\/Yasee\/yasee_ios"]},{"identifiers":["doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleDevice","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Check","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Devices","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Notify","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Yasee"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/CheckSign","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/CheckStepPtl","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/DecodeCmd","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Platform"]},{"title":"Structures","identifiers":["doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/AdvertisementData","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleChars","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleConfig","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleService","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Cmd","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/ErrObj","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyDeviceData","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyResp","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/User"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyBleDevice","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyBleState","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyCall"]},{"title":"Enumerations","identifiers":["doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleState","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/CheckStep","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyType","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/PlatformType","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Usage","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/YError"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yasee_ios"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yasee_ios"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Framework","title":"yasee_ios","modules":[{"name":"yasee_ios"}],"externalID":"yasee_ios","symbolKind":"module","role":"collection"},"sections":[],"hierarchy":{"paths":[[]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios","interfaceLanguage":"swift"},"references":{"doc://com.yasee.yasee/documentation/yasee_ios/Platform":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Platform","kind":"identifier"}],"title":"Platform","url":"\/documentation\/yasee_ios\/platform","navigatorTitle":[{"text":"Platform","kind":"identifier"}],"abstract":[{"type":"text","text":"平台协议类"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Platform"},"doc://com.yasee.yasee/documentation/yasee_ios/BleService":{"title":"BleService","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleService","navigatorTitle":[{"kind":"identifier","text":"BleService"}],"url":"\/documentation\/yasee_ios\/bleservice","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"设备包含的 服务 模型"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BleService"}]},"doc://com.yasee.yasee/documentation/yasee_ios/PlatformType":{"role":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/PlatformType","kind":"symbol","abstract":[{"type":"text","text":"平台支持的类型"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlatformType","kind":"identifier"}],"url":"\/documentation\/yasee_ios\/platformtype","navigatorTitle":[{"text":"PlatformType","kind":"identifier"}],"title":"PlatformType","type":"topic"},"doc://com.yasee.yasee/documentation/yasee_ios/BleDevice":{"url":"\/documentation\/yasee_ios\/bledevice","title":"BleDevice","kind":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleDevice","navigatorTitle":[{"text":"BleDevice","kind":"identifier"}],"abstract":[{"type":"text","text":"蓝牙设备"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BleDevice"}],"role":"symbol"},"doc://com.yasee.yasee/documentation/yasee_ios/CheckStepPtl":{"abstract":[{"type":"text","text":"根据检测项获取 交互步骤"}],"role":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/CheckStepPtl","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckStepPtl"}],"navigatorTitle":[{"kind":"identifier","text":"CheckStepPtl"}],"type":"topic","url":"\/documentation\/yasee_ios\/checkstepptl","kind":"symbol","title":"CheckStepPtl"},"doc://com.yasee.yasee/documentation/yasee_ios/NotifyDeviceData":{"title":"NotifyDeviceData","abstract":[{"type":"text","text":"设备数据"}],"kind":"symbol","url":"\/documentation\/yasee_ios\/notifydevicedata","role":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyDeviceData","navigatorTitle":[{"text":"NotifyDeviceData","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotifyDeviceData","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/NotifyCall":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotifyCall"}],"abstract":[{"type":"text","text":"通知块"},{"type":"text","text":"\n"},{"text":"主要内容为 通知的回调","type":"text"}],"title":"NotifyCall","url":"\/documentation\/yasee_ios\/notifycall","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotifyCall","kind":"identifier"}],"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyCall"},"doc://com.yasee.yasee/documentation/yasee_ios/Devices":{"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Devices","abstract":[{"type":"text","text":"设备管理类"}],"url":"\/documentation\/yasee_ios\/devices","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Devices","kind":"identifier"}],"type":"topic","title":"Devices","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Devices"}],"kind":"symbol"},"doc://com.yasee.yasee/documentation/yasee_ios":{"role":"collection","title":"yasee_ios","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios","url":"\/documentation\/yasee_ios","abstract":[],"kind":"symbol","type":"topic"},"doc://com.yasee.yasee/documentation/yasee_ios/NotifyBleState":{"title":"NotifyBleState","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyBleState","navigatorTitle":[{"kind":"identifier","text":"NotifyBleState"}],"url":"\/documentation\/yasee_ios\/notifyblestate","type":"topic","abstract":[{"type":"text","text":"==================================== T ======================================"},{"text":" ","type":"text"},{"type":"text","text":"蓝牙 状态"}],"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotifyBleState"}]},"doc://com.yasee.yasee/documentation/yasee_ios/YError":{"abstract":[{"text":"错误信息","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/YError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"YError","kind":"identifier"}],"navigatorTitle":[{"text":"YError","kind":"identifier"}],"type":"topic","url":"\/documentation\/yasee_ios\/yerror","kind":"symbol","title":"YError"},"doc://com.yasee.yasee/documentation/yasee_ios/BleConfig":{"role":"symbol","title":"BleConfig","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleConfig","navigatorTitle":[{"kind":"identifier","text":"BleConfig"}],"kind":"symbol","url":"\/documentation\/yasee_ios\/bleconfig","type":"topic","abstract":[{"type":"text","text":"蓝牙配置"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BleConfig","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/BleState":{"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleState","url":"\/documentation\/yasee_ios\/blestate","title":"BleState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BleState"}],"role":"symbol","navigatorTitle":[{"text":"BleState","kind":"identifier"}],"abstract":[{"type":"text","text":"蓝牙 状态"}],"kind":"symbol"},"doc://com.yasee.yasee/documentation/yasee_ios/User":{"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/User","abstract":[{"type":"text","text":"人员信息模型"}],"type":"topic","url":"\/documentation\/yasee_ios\/user","navigatorTitle":[{"text":"User","kind":"identifier"}],"kind":"symbol","title":"User","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"User","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/Notify":{"abstract":[{"text":"通知管理类","type":"text"}],"title":"Notify","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Notify","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Notify","url":"\/documentation\/yasee_ios\/notify","navigatorTitle":[{"text":"Notify","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/DecodeCmd":{"role":"symbol","type":"topic","url":"\/documentation\/yasee_ios\/decodecmd","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/DecodeCmd","title":"DecodeCmd","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DecodeCmd","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"解析数据的协议"}],"navigatorTitle":[{"text":"DecodeCmd","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/Yasee/yasee_ios":{"title":"Yasee iOS Api 文档","identifier":"doc:\/\/com.yasee.yasee\/documentation\/Yasee\/yasee_ios","url":"\/documentation\/yasee\/yasee_ios","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.yasee.yasee/documentation/yasee_ios/NotifyBleDevice":{"title":"NotifyBleDevice","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyBleDevice","navigatorTitle":[{"text":"NotifyBleDevice","kind":"identifier"}],"url":"\/documentation\/yasee_ios\/notifybledevice","type":"topic","kind":"symbol","abstract":[{"text":"搜索的设备信息","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"NotifyBleDevice","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/CheckStep":{"abstract":[{"type":"text","text":"检测步骤"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckStep"}],"title":"CheckStep","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/CheckStep","url":"\/documentation\/yasee_ios\/checkstep","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CheckStep","kind":"identifier"}],"type":"topic"},"doc://com.yasee.yasee/documentation/yasee_ios/CheckSign":{"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/CheckSign","kind":"symbol","title":"CheckSign","role":"symbol","url":"\/documentation\/yasee_ios\/checksign","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CheckSign"}],"navigatorTitle":[{"text":"CheckSign","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"签名、 校验"}]},"doc://com.yasee.yasee/documentation/yasee_ios/Yasee":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Yasee","kind":"identifier"}],"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Yasee","kind":"symbol","abstract":[{"text":"Yasee SDK 顶级控制单元","type":"text"}],"url":"\/documentation\/yasee_ios\/yasee","type":"topic","role":"symbol","title":"Yasee","navigatorTitle":[{"text":"Yasee","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/yasee_iosVersionString":{"title":"yasee_iosVersionString","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/yasee_iosVersionString","url":"\/documentation\/yasee_ios\/yasee_iosversionstring","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Project version string for yasee_ios."}],"role":"symbol","fragments":[{"text":"yasee_iosVersionString","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/ErrObj":{"type":"topic","url":"\/documentation\/yasee_ios\/errobj","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrObj"}],"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/ErrObj","kind":"symbol","navigatorTitle":[{"text":"ErrObj","kind":"identifier"}],"abstract":[{"type":"text","text":"错误内容"}],"title":"ErrObj","role":"symbol"},"doc://com.yasee.yasee/documentation/yasee_ios/AdvertisementData":{"kind":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/AdvertisementData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvertisementData"}],"navigatorTitle":[{"text":"AdvertisementData","kind":"identifier"}],"title":"AdvertisementData","abstract":[{"text":"Codable AdvertisementData 数据","type":"text"}],"url":"\/documentation\/yasee_ios\/advertisementdata","role":"symbol","type":"topic"},"doc://com.yasee.yasee/documentation/yasee_ios/yasee_iosVersionNumber":{"title":"yasee_iosVersionNumber","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/yasee_iosVersionNumber","url":"\/documentation\/yasee_ios\/yasee_iosversionnumber","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Project version number for yasee_ios."}],"role":"symbol","fragments":[{"text":"yasee_iosVersionNumber","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/Check":{"abstract":[{"text":"检测项","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Check","kind":"identifier"}],"title":"Check","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Check"}],"type":"topic","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Check","url":"\/documentation\/yasee_ios\/check"},"doc://com.yasee.yasee/documentation/yasee_ios/Cmd":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Cmd","kind":"identifier"}],"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Cmd","kind":"symbol","title":"Cmd","abstract":[{"type":"text","text":"交互命令"}],"navigatorTitle":[{"text":"Cmd","kind":"identifier"}],"role":"symbol","url":"\/documentation\/yasee_ios\/cmd"},"doc://com.yasee.yasee/documentation/yasee_ios/BleChars":{"type":"topic","url":"\/documentation\/yasee_ios\/blechars","title":"BleChars","abstract":[{"text":"设备包含的 特征 模型","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/BleChars","kind":"symbol","navigatorTitle":[{"text":"BleChars","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BleChars","kind":"identifier"}]},"doc://com.yasee.yasee/documentation/yasee_ios/NotifyType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotifyType"}],"navigatorTitle":[{"text":"NotifyType","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"通知的类型","type":"text"}],"role":"symbol","url":"\/documentation\/yasee_ios\/notifytype","title":"NotifyType","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyType"},"doc://com.yasee.yasee/documentation/yasee_ios/Usage":{"title":"Usage","abstract":[{"type":"text","text":"特征 & 服务的含义"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Usage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/Usage","url":"\/documentation\/yasee_ios\/usage","navigatorTitle":[{"text":"Usage","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.yasee.yasee/documentation/yasee_ios/NotifyResp":{"identifier":"doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/NotifyResp","abstract":[{"type":"text","text":"数据 通知顶级结构"}],"navigatorTitle":[{"text":"NotifyResp","kind":"identifier"}],"kind":"symbol","title":"NotifyResp","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotifyResp","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/yasee_ios\/notifyresp"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"title":"Articles","identifiers":["doc:\/\/com.yasee.yasee\/documentation\/Yasee\/yasee_ios"],"generated":true},{"title":"Variables","identifiers":["doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/yasee_iosVersionNumber","doc:\/\/com.yasee.yasee\/documentation\/yasee_ios\/yasee_iosVersionString"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null}]}]}